// <auto-generated />
using System;
using LibraryProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryProject.Data.Migrations
{
    [DbContext(typeof(ApplicationContextDb))]
    partial class ApplicationContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryProject.Domain.Entities.BookReservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReserveEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReserveStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookReservation");
                });

            modelBuilder.Entity("LibraryProject.Domain.Entities.BookReservationHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReserveEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReserveStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookReservationHistory");
                });

            modelBuilder.Entity("LibraryProject.Domain.Entities.BooksEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Auther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookPublishYear")
                        .HasColumnType("int");

                    b.Property<string>("ControllerUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Auther = "Levis Corrol",
                            BookName = "Alis Harikalar Diyarında",
                            BookPublishYear = 2022,
                            ControllerUserName = "Admin User",
                            CreatedDate = new DateTime(2022, 3, 3, 0, 23, 58, 562, DateTimeKind.Local).AddTicks(3538),
                            ISBN = "975-17-1627-6",
                            Price = 20m,
                            Status = 3
                        },
                        new
                        {
                            Id = 2,
                            Auther = "Andersen",
                            BookName = "Andersen Masalları",
                            BookPublishYear = 2005,
                            ControllerUserName = "Admin User",
                            CreatedDate = new DateTime(2022, 3, 3, 0, 23, 58, 564, DateTimeKind.Local).AddTicks(364),
                            ISBN = "975-17-1627-6",
                            Price = 20m,
                            Status = 3
                        },
                        new
                        {
                            Id = 3,
                            Auther = "Aisopos",
                            BookName = "Ezop Masalları",
                            BookPublishYear = 1995,
                            ControllerUserName = "Admin User",
                            CreatedDate = new DateTime(2022, 3, 3, 0, 23, 58, 564, DateTimeKind.Local).AddTicks(431),
                            ISBN = "975-17-1627-6",
                            Price = 20m,
                            Status = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
